const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.wrap,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Behaviors.Orbit,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.find,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Gamepad: 0},
	{Keyboard: 0},
	{Audio: 0},
	{AJAX: 0},
	{Estado: 0},
	{pHP: 0},
	{pHPMAX: 0},
	{Attack: 0},
	{Crouch: 0},
	{Reload: 0},
	{CoyoteTimer: 0},
	{RollOff: 0},
	{Jumps: 0},
	{JumpsMAX: 0},
	{Phase: 0},
	{Jumped: 0},
	{Platform: 0},
	{Timer: 0},
	{Tween: 0},
	{MoveTo: 0},
	{Player_Base: 0},
	{Flash: 0},
	{Player_Anim: 0},
	{pDmg: 0},
	{Go: 0},
	{Bullet: 0},
	{Hook: 0},
	{Player_Capa: 0},
	{Pin: 0},
	{SlowFall_Effect: 0},
	{Lock: 0},
	{AIM: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Water: 0},
	{Zona: 0},
	{GameStatus: 0},
	{Stage: 0},
	{MinutesSTAGE: 0},
	{SecondsSTAGE: 0},
	{Turno: 0},
	{Enemies: 0},
	{Alert: 0},
	{InAlert: 0},
	{Mili: 0},
	{cena: 0},
	{cena_Final: 0},
	{Take: 0},
	{GameManager: 0},
	{CheckPointNumb: 0},
	{Usado: 0},
	{Checkpoint: 0},
	{Fall: 0},
	{FallDetetcted: 0},
	{FallRespawn: 0},
	{Criou: 0},
	{myUID: 0},
	{Dir: 0},
	{BossName: 0},
	{Spawnador: 0},
	{PortaX1: 0},
	{PortaY1: 0},
	{PortaX2: 0},
	{PortaY2: 0},
	{PlayerDir: 0},
	{Function: 0},
	{Type: 0},
	{GatilhoPorta1: 0},
	{SpawnadorCover: 0},
	{GatilhoCutscene: 0},
	{Order: 0},
	{Troncador: 0},
	{MaxTroncos: 0},
	{TroncoTimer: 0},
	{TroncoDist: 0},
	{GerTroncos: 0},
	{TroncoStart: 0},
	{Intervalo: 0},
	{DropMaterial: 0},
	{BossOff: 0},
	{BossRoom: 0},
	{Solid: 0},
	{Tilemap_Solidos: 0},
	{Tilemap_BG: 0},
	{Tiledbg_Pause: 0},
	{TiledBg_Forest: 0},
	{Rotate: 0},
	{BG_Gear1: 0},
	{BG_Gear2: 0},
	{BG_Gears3: 0},
	{BG_Gears4: 0},
	{TiledBg_MenuPause: 0},
	{Tilemap_Geral: 0},
	{TiledBg_Placas: 0},
	{TiledBg_Solido: 0},
	{Arbustinho: 0},
	{OverSmasher: 0},
	{WaterFallEffect: 0},
	{Smoke: 0},
	{Tipo: 0},
	{Velocidade: 0},
	{Fade: 0},
	{Sine: 0},
	{Alert1: 0},
	{Jumpthru: 0},
	{Plataform_Elevator: 0},
	{Position: 0},
	{Fix: 0},
	{Plataform_Gear: 0},
	{Gear1: 0},
	{Off: 0},
	{tDmg: 0},
	{Element: 0},
	{Spikes: 0},
	{TiledBg_Alert: 0},
	{Sparks: 0},
	{Treadmill: 0},
	{Unlock: 0},
	{MyBoss: 0},
	{Porta1: 0},
	{Explosion1: 0},
	{Name: 0},
	{Description: 0},
	{Animation: 0},
	{Upgrade: 0},
	{BlocoHard: 0},
	{Cover1: 0},
	{Mission: 0},
	{Particles: 0},
	{ElevatorGear: 0},
	{SparkWall: 0},
	{TroncoPlat: 0},
	{Garota: 0},
	{Status: 0},
	{RescuedGirl: 0},
	{DragonBreath: 0},
	{FireDrop: 0},
	{WaterFall: 0},
	{Pos_Impact: 0},
	{Pos_Idle: 0},
	{Smash: 0},
	{Smasher: 0},
	{Material: 0},
	{EffectFire: 0},
	{HeartUp: 0},
	{EffectSmoke: 0},
	{Effect_ImpactFlash: 0},
	{Selector: 0},
	{Flasher: 0},
	{dialogo_Position: 0},
	{dialogo_pos: 0},
	{txtFonte: 0},
	{CheckPointEffect1: 0},
	{HUD_Reload: 0},
	{txtMicro: 0},
	{GO_Txt: 0},
	{eHPMAX: 0},
	{MyBossUID: 0},
	{HUD_bHPBar: 0},
	{HUD_bHPBarBack: 0},
	{HUD_HPBar: 0},
	{HUDbHPBar_Back: 0},
	{Logo: 0},
	{Start: 0},
	{HUD_BarBack: 0},
	{Txt: 0},
	{MyUpgrade: 0},
	{Janela_Upgrade: 0},
	{HUD_PlayerName: 0},
	{Dialogo_Avatar: 0},
	{Next: 0},
	{Janela_Dialogo: 0},
	{TiledBg_MissionStart: 0},
	{AlertBack: 0},
	{Screen: 0},
	{txtAlert: 0},
	{Wrap: 0},
	{Camuflage1: 0},
	{Dic_Data: 0},
	{Array_Upgrades: 0},
	{Array_Dialogo: 0},
	{Array_Story: 0},
	{FB_Body: 0},
	{PosIdle: 0},
	{PosOpen: 0},
	{FB_Chest_L: 0},
	{FB_Chest_R: 0},
	{Patrol: 0},
	{Stun: 0},
	{FB_Eye: 0},
	{FB_Gear1: 0},
	{Orbit: 0},
	{FB_Hand_L: 0},
	{FB_Sholder_R: 0},
	{FB_Sholder_L: 0},
	{Boss: 0},
	{BossNumber: 0},
	{eHP: 0},
	{Block: 0},
	{Modo: 0},
	{FB_Heart: 0},
	{FB_Hand_R: 0},
	{FB_Acesso_L: 0},
	{FB_Acesso_R: 0},
	{SmashImpact: 0},
	{My_Hand: 0},
	{Sprite3: 0},
	{FB_LaserPoint: 0},
	{FB_Rastreio: 0},
	{bDmg: 0},
	{pShot: 0},
	{Direct: 0},
	{DestroyDirect: 0},
	{dWall: 0},
	{FlashBlock: 0},
	{Bounce: 0},
	{B1Lightning: 0},
	{B1Off: 0},
	{Boss1: 0},
	{Sprite2: 0},
	{Back: 0},
	{B1_Saw: 0},
	{PosAtk: 0},
	{Boss1x: 0},
	{Boss1Off: 0},
	{E1_Shot: 0},
	{MyE1: 0},
	{E1_Vision: 0},
	{CreateVision: 0},
	{ShotDir: 0},
	{Enemy1: 0},
	{Enemy2: 0},
	{FullActive: 0},
	{Cannon: 0},
	{FireBallShot: 0},
	{Speed: 0},
	{HMissile: 0},
	{Enemy3: 0},
	{Distance: 0},
	{Enemy4: 0},
	{Ativo: 0},
	{Miner: 0},
	{Boca: 0},
	{TriCannon: 0},
	{CannonShot: 0},
	{FireballTrace: 0},
	{Enemy5: 0},
	{TiledBackground: 0},
	{Laser: 0},
	{Sprite4: 0},
	{TiledBackground2: 0},
	{GatilhoTrap: 0},
	{Grid: 0},
	{SmasherCore: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{gTDmg: 0},
	{gDetec: 0},
	{gBullet: 0},
	{gEffect: 0},
	{gEnemy: 0},
	{gSolidos: 0},
	{gPBack: 0},
	{gColetaveis: 0},
	{gPdmg: 0},
	{gCover: 0},
	{gPhaserTr: 0},
	{gSholderG: 0},
	{Control: 0},
	{Seconds: 0},
	{Minutes: 0},
	{SecondsMINUS: 0},
	{MinutesMINUS: 0},
	{CheckPoint: 0},
	{UpgradesGOT: 0},
	{UPGRADES: 0},
	{BOSSES: 0},
	{Detected: 0},
	{diferenca: 0},
	{subtracao: 0},
	{mais: 0},
	{menos: 0},
	{Tag: 0},
	{cena_FINAL: 0},
	{dialogo_msg: 0},
	{dialogo_msgFinal: 0},
	{inDialogo: 0},
	{Pdialogo_msg: 0},
	{Pdialogo_msgFinal: 0},
	{ShotAngle: 0},
	{story_msg: 0},
	{story_msgFinal: 0},
	{PStory_Msg: 0},
	{PStory_MsgFinal: 0}
];

self.InstanceType = {
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Player_Base: class extends self.ISpriteInstance {},
	Player_Anim: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	Hook: class extends self.ISpriteInstance {},
	Player_Capa: class extends self.ISpriteInstance {},
	SlowFall_Effect: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Zona: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	Fall: class extends self.ISpriteInstance {},
	FallDetetcted: class extends self.ISpriteInstance {},
	FallRespawn: class extends self.ISpriteInstance {},
	Spawnador: class extends self.ISpriteInstance {},
	GatilhoPorta1: class extends self.ISpriteInstance {},
	SpawnadorCover: class extends self.ISpriteInstance {},
	GatilhoCutscene: class extends self.ISpriteInstance {},
	Troncador: class extends self.ISpriteInstance {},
	GerTroncos: class extends self.ISpriteInstance {},
	TroncoStart: class extends self.ISpriteInstance {},
	DropMaterial: class extends self.ISpriteInstance {},
	BossRoom: class extends self.ISpriteInstance {},
	Tilemap_Solidos: class extends self.ITilemapInstance {},
	Tilemap_BG: class extends self.ITilemapInstance {},
	Tiledbg_Pause: class extends self.ITiledBackgroundInstance {},
	TiledBg_Forest: class extends self.ITiledBackgroundInstance {},
	BG_Gear1: class extends self.ISpriteInstance {},
	BG_Gear2: class extends self.ISpriteInstance {},
	BG_Gears3: class extends self.ISpriteInstance {},
	BG_Gears4: class extends self.ISpriteInstance {},
	TiledBg_MenuPause: class extends self.ITiledBackgroundInstance {},
	Tilemap_Geral: class extends self.ITilemapInstance {},
	TiledBg_Placas: class extends self.ITiledBackgroundInstance {},
	TiledBg_Solido: class extends self.ITiledBackgroundInstance {},
	Arbustinho: class extends self.ISpriteInstance {},
	OverSmasher: class extends self.ISpriteInstance {},
	WaterFallEffect: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	Alert1: class extends self.ISpriteInstance {},
	Plataform_Elevator: class extends self.ISpriteInstance {},
	Plataform_Gear: class extends self.ISpriteInstance {},
	Gear1: class extends self.ISpriteInstance {},
	Spikes: class extends self.ISpriteInstance {},
	TiledBg_Alert: class extends self.ITiledBackgroundInstance {},
	Sparks: class extends self.ISpriteInstance {},
	Treadmill: class extends self.ISpriteInstance {},
	Porta1: class extends self.ISpriteInstance {},
	Explosion1: class extends self.ISpriteInstance {},
	Upgrade: class extends self.ISpriteInstance {},
	BlocoHard: class extends self.ISpriteInstance {},
	Cover1: class extends self.ISpriteInstance {},
	Mission: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ElevatorGear: class extends self.ISpriteInstance {},
	SparkWall: class extends self.ISpriteInstance {},
	TroncoPlat: class extends self.ISpriteInstance {},
	RescuedGirl: class extends self.ISpriteInstance {},
	DragonBreath: class extends self.ISpriteInstance {},
	FireDrop: class extends self.ISpriteInstance {},
	WaterFall: class extends self.ISpriteInstance {},
	Smasher: class extends self.ISpriteInstance {},
	Material: class extends self.ISpriteInstance {},
	EffectFire: class extends self.ISpriteInstance {},
	HeartUp: class extends self.ISpriteInstance {},
	EffectSmoke: class extends self.ISpriteInstance {},
	Effect_ImpactFlash: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	txtFonte: class extends self.ISpriteFontInstance {},
	CheckPointEffect1: class extends self.ISpriteInstance {},
	HUD_Reload: class extends self.ITiledBackgroundInstance {},
	txtMicro: class extends self.ISpriteFontInstance {},
	GO_Txt: class extends self.ISpriteInstance {},
	HUD_bHPBar: class extends self.ITiledBackgroundInstance {},
	HUD_bHPBarBack: class extends self.ISpriteInstance {},
	HUD_HPBar: class extends self.ITiledBackgroundInstance {},
	HUDbHPBar_Back: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	HUD_BarBack: class extends self.ITiledBackgroundInstance {},
	Janela_Upgrade: class extends self.ISpriteInstance {},
	HUD_PlayerName: class extends self.ISpriteInstance {},
	Dialogo_Avatar: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	Janela_Dialogo: class extends self.ISpriteInstance {},
	TiledBg_MissionStart: class extends self.ITiledBackgroundInstance {},
	AlertBack: class extends self.ISpriteInstance {},
	Screen: class extends self.ISpriteInstance {},
	txtAlert: class extends self.ISpriteFontInstance {},
	Camuflage1: class extends self.ISpriteInstance {},
	Dic_Data: class extends self.IDictionaryInstance {},
	Array_Upgrades: class extends self.IArrayInstance {},
	Array_Dialogo: class extends self.IArrayInstance {},
	Array_Story: class extends self.IArrayInstance {},
	FB_Body: class extends self.ITiledBackgroundInstance {},
	FB_Chest_L: class extends self.ISpriteInstance {},
	FB_Chest_R: class extends self.ISpriteInstance {},
	FB_Eye: class extends self.ISpriteInstance {},
	FB_Gear1: class extends self.ISpriteInstance {},
	FB_Hand_L: class extends self.ISpriteInstance {},
	FB_Sholder_R: class extends self.ISpriteInstance {},
	FB_Sholder_L: class extends self.ISpriteInstance {},
	FB_Heart: class extends self.ISpriteInstance {},
	FB_Hand_R: class extends self.ISpriteInstance {},
	FB_Acesso_L: class extends self.ISpriteInstance {},
	FB_Acesso_R: class extends self.ISpriteInstance {},
	SmashImpact: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	FB_LaserPoint: class extends self.ISpriteInstance {},
	FB_Rastreio: class extends self.ISpriteInstance {},
	B1Lightning: class extends self.ISpriteInstance {},
	B1Off: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	B1_Saw: class extends self.ISpriteInstance {},
	Boss1x: class extends self.ISpriteInstance {},
	Boss1Off: class extends self.ISpriteInstance {},
	E1_Shot: class extends self.ISpriteInstance {},
	E1_Vision: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	FireBallShot: class extends self.ISpriteInstance {},
	HMissile: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	Miner: class extends self.ISpriteInstance {},
	TriCannon: class extends self.ISpriteInstance {},
	CannonShot: class extends self.ISpriteInstance {},
	FireballTrace: class extends self.ISpriteInstance {},
	Enemy5: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Laser: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	GatilhoTrap: class extends self.ISpriteInstance {},
	Grid: class extends self.ITiledBackgroundInstance {},
	SmasherCore: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	gTDmg: class extends self.ISpriteInstance {},
	gDetec: class extends self.ISpriteInstance {},
	gBullet: class extends self.ISpriteInstance {},
	gEffect: class extends self.ISpriteInstance {},
	gEnemy: class extends self.ISpriteInstance {},
	gSolidos: class extends self.ISpriteInstance {},
	gPBack: class extends self.ISpriteInstance {},
	gColetaveis: class extends self.ISpriteInstance {},
	gPdmg: class extends self.ISpriteInstance {},
	gCover: class extends self.ISpriteInstance {},
	gPhaserTr: class extends self.ISpriteInstance {},
	gSholderG: class extends self.ISpriteInstance {}
}